### ISSUE TITLE
Raw attachment mime stuff included with mml-attach-file shows up in email

### ISSUE THREAD

**Issue by godfrey-cw** [org-mime/org-mime#37]
I'm getting things like:

<#part type="application/pdf" filename="/home/charlie/Desktop/siamtodo.pdf" disposition=attachment description="SIAM schedule"> <#/part>

showing up at the other end of emails when using `mml-attach-file` before running `org-mime-htmlize`. Do I need to run `org-mime-htmlize` *first*, and *then* attach the file? 

Apologies if this is a silly question.

**Comment by redguardtoo** [comment]
I'm not familiar with html mail actually. I guess you need run `mml-attach-file` after `org-mime-htmlize` which is just converter of org to html. Or else, you need run `org-insert-link-global` (I prefer manually input file link though, with yasnippet help).

**Comment by godfrey-cw** [comment]
I've tried `org-insert-link-global` without success. I'm mostly trying to attach pdfs, so for instance I tried `[[file:/home/me/Desktop/some.pdf]][A pdf]]`, but all that came out in the email was an unlinked "A pdf."

Is there something I'm getting wrong here?

**Comment by redguardtoo** [comment]
I see. You need run org-mime-htmlize at first, then manually attach file. 

It's org-mode's export function which converts org to html. So you can only attach jpg and png link mail body. For other files, you have to attach them manually.

**Comment by rememberYou** [comment]
Hello,

First of all, thank you for this beautiful and useful package. I don't know if a solution has been found since. However, I still have the problem when I attach a PDF or other file and a signature.

On another issue [#12](https://github.com/org-mime/org-mime/issues/12), you recommend to use the `org-mime-find-html-start` variable so that `org-htmlize` ignores the lines related to the join of a file or a signature. Wouldn't it be better to automatically ignore these lines in this package? Probably this is a general behavior that every user would like to have. It would save `org-mime` users from having to fill in every case to be ignored with `org-mime-find-html-start`.

**Comment by redguardtoo** [comment]
23cc52b donot htmlize security signature and attachment (Chen Bin)

**Comment by rememberYou** [comment]
Thanks for the commit of the `org-mime-extract-non-org` function.
